apiVersion: v1
kind: Secret
metadata:
  name: kubernal-api-secret
  labels:
    app: kubernal-api
    kubernal.io/managed-by: kubernal
type: Opaque
stringData:
  DATABASE_URL: 'postgresql://kubernal:kubernal_dev@postgres-service:5432/kubernal_idp?schema=public'
