apiVersion: v1
kind: Service
metadata:
  name: {{name}}
  labels:
    app: {{name}}
    managed-by: kubernal-idp
spec:
  type: {{`{{ .Values.service.type }}`}}
  ports:
    - port: {{`{{ .Values.service.port }}`}}
      targetPort: {{port}}
      protocol: TCP
      name: http
  selector:
    app: {{name}}
