apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernal-api
  labels:
    app: kubernal-api
    kubernal.io/managed-by: kubernal
rules:
  - apiGroups: ['']
    resources: ['namespaces']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'patch']
  - apiGroups: ['']
    resources: ['resourcequotas', 'limitranges']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'patch']
  - apiGroups: ['']
    resources: ['serviceaccounts']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'patch']
  - apiGroups: ['rbac.authorization.k8s.io']
    resources: ['roles', 'rolebindings']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'patch']
  - apiGroups: ['']
    resources: ['secrets', 'configmaps']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'patch']
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['autoscaling']
    resources: ['horizontalpodautoscalers']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources: ['nodes']
    verbs: ['get', 'list']
