---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgres-secret
  namespace: kubernal-staging
spec:
  encryptedData:
    POSTGRES_DB: AgBYsK2oK5Lh1cAVFrvSjVBnMUlHk+ydGfmidQjaq957RgYAxLhmvXcWGSpa42RtSHnNTD8xftc/2LjUSCOBVXrTaNX3O0AhGFf3Y+IZoIzaw3ELCqBbI+e/o9owJ+S3IsQkV4a2FYjoSnLVC5I3r4x/JmTv76leTCNDfrzljfK9guV6fsbLPaQeA3aVhFUxc5zObW1iPIGgYS9GearUCDy6qIYFSKJYnHiDd1Ok4M7CFZt400EBN2KCtr1JvJywxr5eOGg2iDth2SVYIbvaRw/Z0Dmu6k+rRIXhEck1z2oO56JIbVubL8BLQVQtJa9HLTe53+xCnNvhOd5rjFwgpfb8tdbM0HOWJJoF97xN3RDvEcX68RmwBRG1zKiv8O1nF8b0je7d6YoRteA9jNTAOQ+T8ujOLDMd1T7IkMlEY97wH7HsDI7jvzjOzwJCqf7wvlcPyGSMlt0Gm1zef9D0z6gfGP2t+Qcb+KFIE3ZlkEgL7mA8d2rNs/FoOq8OBqwXvsd232AGaS8kFvEeMz65+fKeHZVpoQplpBX56NMlXdDHPxSUyYuM9urBs8/KkqQd6hxWzamSCm/Kvi6EGFyUULUqzJRbHwMDiwIgC9ZOLU8yuJmt/ukrC98Hkj9cCu8AiVZDR/tCnjnreD39gspl/3FBx5zYE7kY1M57TSlem3x48zMu/qlwcl3UOXwq40bwbEi8umGewoJr/1eFKZc=
    POSTGRES_PASSWORD: AgCRXBMBetfxIHjsu1kqEP4XHP+PDkiDi9nGzrxWi3Iom5/69vL4meAFF6GyZdpUDGd7Tt/44gnf5S+QEWXjpKdBO9ZUjG4KVgvfOjr9GbZ3vqJ5DmZ5Xjn/zOwjMbXexasXXyH6DGRZp4F+RnznbOaWeBCOKI7Ef3+uDbLtHEDNRu4kr5ZnAllSvAB4LYJWz6SH4JjnXXxiYmYWFwioTCoRtP5yaf9XyEg/NHBJsQJf6OriGkdGJjJ9657KeBuHmwmhu3PmCfobNZjobv0kyg1vJ+HhQXum2RkzfKHQuzWHQaG4hT3HwhHS38j66eQmLWua0rk1necDpjCv7hk1/gGkoHKkFF3G7SblAgfBVghV7CNhJoAhUs4neUv7IIBR8cAuPYy1rF/ARrv5JMNHECWMn+J5Ms7TWC/7SSfI9uz1Hlu43pbI09gj2RW9Jk+ICTvxpp1u/JafuCk48RxisGJS4ZNMTBWB5zipv/CBoTR+l8/Jfud0CF9xKQnRvGH2ehQ2uY3VMIAkk0Xq9mQX5HPMN7pfF9pnq7SqIzMEU8vdaezsLGkjvCSb0auz1445wkHf34fH7RrW5hDz6NHJZF76SiTUYpo5rY5kpp5ZNJi0mvFa8ipgs4uXIZ2UGtj/8s/RNcQl2a3QHox9J+WMN68I8FQs6wMbKTn7VmgeKnzRb2yVIq5CD6Zbj/FyhZonZbtF6YgiQqzNVdKW02RQAXuY
    POSTGRES_USER: AgA+0SgjPooaLiISSarZ4wU/B/nw9KfMIPjnUJGCs+MnP0o0dteRftFlXeFQ5eGDqF6xv5RAYyB+dTlAT2iv9XZN6eVJ4nY6SZxWRU19gL0n6g8RFNoBkV4lxf8P6deOjjNQSdpVfwXiA/CRDik0XTuSdlEdTfNBxNB+hWbvUIZSNR+2ahE9rc7e2b904/KGT5puYeMlcartukc7bVG0hjoj/4EO9B1xpfmWOffBg0evyb8KyyShZTQF6zLXJCEMOnWH2Uzbn1OQhF3ZfK5xuTdAKAkHBY5nP81mFeBgUIYbIYmI7x8nXnX4fND9RTPIruY2e6dUg8EzUKqpEFHBGntMFlke8qLtQ2toRgc0PHaMX7rnmawpxXt/Q9N+pqAFwwX06yxEYL8Qt0F9w++lrrN1s9gfxLman0X0fKoTbRuhnrBzX4N+8is7XJwKZxH/2WWPsy8GCp5Ivni6Jsrgbwco5c4dsrbaCuEiMnnI7+bIoi/FgRKqOSU5awu4607uf3yfPEDscl1vdpSvgeI8eXZ2U4w7V6CSonKXEXe6FNGi4YUwegE6myyVqFw/DqS2T0Q3SKQkWr7emFTLCtTW1VsoRiR6EXalaS7Fiu4uhT/WYT7S5vP4TSey1ZYgrh655qJpcK+0F/UeQBhzuilzQP50nquglkzX/jTTFwmt7kQIPpnK3ILPzKe0sXVAXD8jPnhFZ/8S2nylzg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: postgres
        kubernal.io/managed-by: kubernal
      name: postgres-secret
      namespace: kubernal-staging
    type: Opaque
