---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgres-secret
  namespace: kubernal-staging
spec:
  encryptedData:
    POSTGRES_DB: AgBi9xJJ+BYig3uf/AclBlU0KpBptgJ23SxUQZrhZiNvcihXj/AJcTjFGswurqioBqGTrTWVaAA4jNcrnTUZl1u25fimGfUDEMrG7PgMiEMpq5Lq+Y321D7XIaKVTfN2YPkvmeoEdybnB6k0WemWGx5miC38y3J9LSMqUPgzcrO6zkRAA0ZTOjHnpXirYH5l2b0Fvwd2zRwCcJpmRFkzOOzbSaaVdmU06noAFlrLDmp1PXn/Y1bcWWm/+vQ9V4cAqRwZhA7yuAIzT40+XkdA/E5P7/jaPtx+BLdXRyrzGeds2k7lL4CYRvohus9cT6zmjri/J/d9diqO+JsSBBWjMGwC8us2N+cUExwOoi1UHrC3gYQVFCTEba3ALfiKjH2I4PitfcKoOaAu9pTyaghEV2hH5UBuPIG0D58qSe9UOBhR1d6iDOj+ZsocsnFriKNxS3hJ5rlT87yuPhXZye/c+FLmljGiTGPCAd8GVyvrtyQOUtRkTMdcbExi8IOip2Q+mcGHmw7M0JEh5ZUi9RxUMc+mDSUn0XMRoJx/bDpp2vYECzGK5uOHWiRV5CCjQzkQRjDw8fzC7vNHN7zK153+rphtI342KGI9txpNY9jaHmZE4VNd4ZHMFeYNX/mPyWkTkZn+Zf0gNp50+ZPcw2jL2TxZEg/3p5coq9RVypwdKSyldn3IpKe7eXYncvIW69T1IvCGNz/w8nh/TBA9ccw=
    POSTGRES_PASSWORD: AgBlqlcyywWQmF1t2YcXK6Yi0G4b0vWg+0T/SzAr3CWc6+T7QJUyvsXMQ9TwMolLQyK0d0d0A/2XO7lMpAZDq3RJ2t+TIrAEpijOUwCCy+u8hKJqoiIWOec4OHaGjVLsPRoLXMZ4SKRRhp6/H44gb0cxsfg345LQORKgZ4860jEAJq2XOjk04PQ1/BOmwgPjh8zZ9Ku/wSq9XsTb873BzyLJdfJOLcTz4tG9jVvMA0TLrgrXWCd6QTTw29cpgmAdPzDTX1fbACJJKe/UtgS5ePR7zrY0dlgK9uh8u7+28nxeUFtsE8lymyhrbAwVjlZz+tp4sz7EmT98Vt7A8K9mLrYwAVZmI43AFsx6HMNRxycdw2ma7bHLXIrmiSWB9bjLnSkn6ZhZ+2wuEgI+wgACWQjJJOlKn/nJCqn3LopY5iyxdoO6S2qQ1yDepw2B+I20oqDDy/V3yrXTn95Qzutk6n7wKnbdxv0hyAeHTzJmE2fNep6u7FF+ER1OZls+t5hsQGcmGuYkOBpJZKG5ojeI0Xo2S7grHbGo/uwDJ/CZUX3cSNGQ9DSLiNuL4iDYcwvdugSMtM0WtsyNy1uRWk3lV5DhR+amburPDhFG6nUvh+FxogNZ5LYPPHAt+CXFPpvG2I9aSwLb84i/BrvMXLeZNlOD6WgXF6ko7fV9G6ywKVxKpJ79tGz+t91+0ljr5v3rfLwNA8ArV0d0Bvx7UdmfmVw5fOhOc1SUAV2QLoQ=
    POSTGRES_USER: AgDAygDLRxrTMJgCxYKXqwjE7tVMUmlG/jKlveC884qXsiixiRW3XASXhKGWeWRzDFOI5doQamP4MNZKmd/N8g0GrhTzAX3h+vELNCyZcGP/hgdf4NY29sD323z/3IdRp0JVwFjIBochmb5J1KwQao3LYJWws3hCG6TYQob4+WF3Wvsvmwq6FiZRyP3CCVtnor5zvydVSAQ9JufZ354HXg7VBRF7uWsOp9JoVOPOAGjbwq70adOKnMjxMIgnKmky+V5S5aqslk+CHlyQNGhkItHwDqTyHdxghE4TPxMQ+IVXldglC+NY5IrTY1NDZa9S7SWVft7xodVOFIkXTFKEQ1+aRMuvFIdw+6UYN+h0jMY264Od5m6BlPvU2kzY0jL30A5in9r3NWDLc6HNZSFSBmWYOdZyxj7JWgB4/5EcUIvjzuf3WRy0YFjnDyP/Nk6YF8hryiVlh2jTlrt35PKFDcoszLz0izYhFi+ZTdcMMNhl7A8bwFvleNiPu1Pz/ymJ06oXrqoDM9+B5Q6HGSJuyGRJ6QvJww8dt98cTHb0GOTZphuOfdsOlAOzLiRDFkfwn+oXIWuMWBerPrUS23Vxkc2m1xxH+gNk7L7IVXiEpUjXkBIqCGvoTE+owzjZaQq4GMjaXAx9LZAugJfbGGPNgypFfFkGuvVnxPSctzpX+sWZFIeznsAMrav9F480oyPTHf7+7OqXHKLgZA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: postgres
        kubernal.io/managed-by: kubernal
      name: postgres-secret
      namespace: kubernal-staging
    type: Opaque
