apiVersion: v1
kind: Namespace
metadata:
  name: kubernal-dev
  labels:
    kubernal.io/environment: dev
    kubernal.io/managed-by: kubernal
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
