// Mock K8s data — fallback when no live cluster is available.
// Mirrors apps/portal/src/mocks/k8s-data.ts data structures.

import type {
  K8sClusterContext,
  K8sPod,
  ArgoAppStatus,
  CrossplaneClaim,
  K8sHPAStatus,
  K8sContainerResources,
  K8sEvent,
  K8sService,
} from '@kubernal/shared-types';

export const MOCK_CLUSTER: K8sClusterContext = {
  name: 'kubernal-prod',
  namespace: 'default',
  apiServerUrl: 'https://api.kubernal.io:6443',
  version: '1.29.2',
  nodeCount: 5,
};

export const MOCK_PODS: K8sPod[] = [
  {
    id: 'pod-pa-prod-1',
    name: 'payment-api-7f8b9c-x2k',
    namespace: 'prod-payment-api',
    nodeName: 'node-01',
    status: 'Running',
    ready: '2/2',
    restarts: 0,
    ip: '10.244.1.20',
    age: '4d',
    startedAt: '2026-05-29T09:12:00Z',
    containers: [
      { name: 'payment-api', image: 'kubernal/payment-api:v2.1.0', ready: true, restartCount: 0, state: 'running', reason: null },
      { name: 'istio-proxy', image: 'istio/proxyv2:1.20.1', ready: true, restartCount: 0, state: 'running', reason: null },
    ],
    labels: { app: 'payment-api', version: 'v2.1.0', environment: 'prod' },
  },
  {
    id: 'pod-pa-prod-2',
    name: 'payment-api-7f8b9c-m4p',
    namespace: 'prod-payment-api',
    nodeName: 'node-02',
    status: 'Running',
    ready: '2/2',
    restarts: 0,
    ip: '10.244.2.35',
    age: '4d',
    startedAt: '2026-05-29T09:12:05Z',
    containers: [
      { name: 'payment-api', image: 'kubernal/payment-api:v2.1.0', ready: true, restartCount: 0, state: 'running', reason: null },
      { name: 'istio-proxy', image: 'istio/proxyv2:1.20.1', ready: true, restartCount: 0, state: 'running', reason: null },
    ],
    labels: { app: 'payment-api', version: 'v2.1.0', environment: 'prod' },
  },
  {
    id: 'pod-pa-prod-3',
    name: 'payment-api-7f8b9c-q8r',
    namespace: 'prod-payment-api',
    nodeName: 'node-03',
    status: 'Running',
    ready: '2/2',
    restarts: 1,
    ip: '10.244.3.18',
    age: '4d',
    startedAt: '2026-05-29T09:14:00Z',
    containers: [
      { name: 'payment-api', image: 'kubernal/payment-api:v2.1.0', ready: true, restartCount: 1, state: 'running', reason: null },
      { name: 'istio-proxy', image: 'istio/proxyv2:1.20.1', ready: true, restartCount: 0, state: 'running', reason: null },
    ],
    labels: { app: 'payment-api', version: 'v2.1.0', environment: 'prod' },
  },
  {
    id: 'pod-pa-prod-4',
    name: 'payment-api-7f8b9c-t5w',
    namespace: 'prod-payment-api',
    nodeName: 'node-04',
    status: 'Running',
    ready: '2/2',
    restarts: 0,
    ip: '10.244.4.22',
    age: '4d',
    startedAt: '2026-05-29T09:12:10Z',
    containers: [
      { name: 'payment-api', image: 'kubernal/payment-api:v2.1.0', ready: true, restartCount: 0, state: 'running', reason: null },
      { name: 'istio-proxy', image: 'istio/proxyv2:1.20.1', ready: true, restartCount: 0, state: 'running', reason: null },
    ],
    labels: { app: 'payment-api', version: 'v2.1.0', environment: 'prod' },
  },
  {
    id: 'pod-pa-prod-5',
    name: 'payment-api-7f8b9c-v9z',
    namespace: 'prod-payment-api',
    nodeName: 'node-05',
    status: 'Pending',
    ready: '0/2',
    restarts: 0,
    ip: null,
    age: '2m',
    startedAt: null,
    containers: [
      { name: 'payment-api', image: 'kubernal/payment-api:v2.1.0', ready: false, restartCount: 0, state: 'waiting', reason: 'ContainerCreating' },
      { name: 'istio-proxy', image: 'istio/proxyv2:1.20.1', ready: false, restartCount: 0, state: 'waiting', reason: 'ContainerCreating' },
    ],
    labels: { app: 'payment-api', version: 'v2.1.0', environment: 'prod' },
  },
  {
    id: 'pod-pa-staging-1',
    name: 'payment-api-3a2c1e-b7n',
    namespace: 'staging-payment-api',
    nodeName: 'node-01',
    status: 'Running',
    ready: '1/1',
    restarts: 0,
    ip: '10.244.1.50',
    age: '1d',
    startedAt: '2026-06-01T11:00:00Z',
    containers: [
      { name: 'payment-api', image: 'kubernal/payment-api:v2.2.0-rc1', ready: true, restartCount: 0, state: 'running', reason: null },
    ],
    labels: { app: 'payment-api', version: 'v2.2.0-rc1', environment: 'staging' },
  },
  {
    id: 'pod-pa-staging-2',
    name: 'payment-api-3a2c1e-k3d',
    namespace: 'staging-payment-api',
    nodeName: 'node-02',
    status: 'Running',
    ready: '1/1',
    restarts: 0,
    ip: '10.244.2.51',
    age: '1d',
    startedAt: '2026-06-01T11:00:05Z',
    containers: [
      { name: 'payment-api', image: 'kubernal/payment-api:v2.2.0-rc1', ready: true, restartCount: 0, state: 'running', reason: null },
    ],
    labels: { app: 'payment-api', version: 'v2.2.0-rc1', environment: 'staging' },
  },
  {
    id: 'pod-pa-staging-3',
    name: 'payment-api-3a2c1e-p6f',
    namespace: 'staging-payment-api',
    nodeName: 'node-03',
    status: 'Running',
    ready: '1/1',
    restarts: 0,
    ip: '10.244.3.52',
    age: '1d',
    startedAt: '2026-06-01T11:00:10Z',
    containers: [
      { name: 'payment-api', image: 'kubernal/payment-api:v2.2.0-rc1', ready: true, restartCount: 0, state: 'running', reason: null },
    ],
    labels: { app: 'payment-api', version: 'v2.2.0-rc1', environment: 'staging' },
  },
  {
    id: 'pod-us-prod-1',
    name: 'user-service-4d5e6f-j2m',
    namespace: 'prod-user-service',
    nodeName: 'node-01',
    status: 'Running',
    ready: '2/2',
    restarts: 0,
    ip: '10.244.1.60',
    age: '6d',
    startedAt: '2026-05-27T07:30:00Z',
    containers: [
      { name: 'user-service', image: 'kubernal/user-service:v1.8.3', ready: true, restartCount: 0, state: 'running', reason: null },
      { name: 'istio-proxy', image: 'istio/proxyv2:1.20.1', ready: true, restartCount: 0, state: 'running', reason: null },
    ],
    labels: { app: 'user-service', version: 'v1.8.3', environment: 'prod' },
  },
  {
    id: 'pod-us-prod-2',
    name: 'user-service-4d5e6f-w8q',
    namespace: 'prod-user-service',
    nodeName: 'node-03',
    status: 'Running',
    ready: '2/2',
    restarts: 0,
    ip: '10.244.3.65',
    age: '6d',
    startedAt: '2026-05-27T07:30:05Z',
    containers: [
      { name: 'user-service', image: 'kubernal/user-service:v1.8.3', ready: true, restartCount: 0, state: 'running', reason: null },
      { name: 'istio-proxy', image: 'istio/proxyv2:1.20.1', ready: true, restartCount: 0, state: 'running', reason: null },
    ],
    labels: { app: 'user-service', version: 'v1.8.3', environment: 'prod' },
  },
  {
    id: 'pod-us-prod-3',
    name: 'user-service-4d5e6f-h5t',
    namespace: 'prod-user-service',
    nodeName: 'node-04',
    status: 'Running',
    ready: '1/2',
    restarts: 5,
    ip: '10.244.4.70',
    age: '6d',
    startedAt: '2026-06-02T16:50:00Z',
    containers: [
      { name: 'user-service', image: 'kubernal/user-service:v1.8.3', ready: true, restartCount: 5, state: 'running', reason: 'CrashLoopBackOff' },
      { name: 'istio-proxy', image: 'istio/proxyv2:1.20.1', ready: true, restartCount: 0, state: 'running', reason: null },
    ],
    labels: { app: 'user-service', version: 'v1.8.3', environment: 'prod' },
  },
  {
    id: 'pod-ns-prod-1',
    name: 'notification-svc-9g1h2i-r3y',
    namespace: 'prod-notification-svc',
    nodeName: 'node-02',
    status: 'Running',
    ready: '1/1',
    restarts: 0,
    ip: '10.244.2.80',
    age: '2d',
    startedAt: '2026-05-31T13:00:00Z',
    containers: [
      { name: 'notification-svc', image: 'kubernal/notification-svc:v1.4.0', ready: true, restartCount: 0, state: 'running', reason: null },
    ],
    labels: { app: 'notification-svc', version: 'v1.4.0', environment: 'prod' },
  },
  {
    id: 'pod-ns-prod-2',
    name: 'notification-svc-9g1h2i-u7e',
    namespace: 'prod-notification-svc',
    nodeName: 'node-05',
    status: 'Failed',
    ready: '0/1',
    restarts: 4,
    ip: null,
    age: '2d',
    startedAt: '2026-05-31T13:00:00Z',
    containers: [
      { name: 'notification-svc', image: 'kubernal/notification-svc:v1.4.0', ready: false, restartCount: 4, state: 'terminated', reason: 'Error' },
    ],
    labels: { app: 'notification-svc', version: 'v1.4.0', environment: 'prod' },
  },
];

export const MOCK_ARGO_STATUSES: Record<string, ArgoAppStatus> = {
  'payment-api-prod': {
    sync: 'Synced',
    health: 'Healthy',
    revision: 'a3f7c1e',
    branch: 'main',
    lastSyncAt: '2026-06-02T15:30:00Z',
    message: null,
  },
  'payment-api-staging': {
    sync: 'OutOfSync',
    health: 'Progressing',
    revision: 'b8d2e5f',
    branch: 'main',
    lastSyncAt: '2026-06-02T12:15:00Z',
    message: 'New image tag detected, auto-sync in progress',
  },
  'user-service-prod': {
    sync: 'Synced',
    health: 'Degraded',
    revision: 'c1a9f4d',
    branch: 'main',
    lastSyncAt: '2026-06-02T10:45:00Z',
    message: 'Pod user-service-4d5e6f-h5t in CrashLoopBackOff',
  },
  'notification-svc-prod': {
    sync: 'Synced',
    health: 'Healthy',
    revision: 'd4e6b2a',
    branch: 'main',
    lastSyncAt: '2026-06-02T14:00:00Z',
    message: null,
  },
};

export const MOCK_CLAIMS: Record<string, CrossplaneClaim[]> = {
  'payment-api-prod': [
    {
      id: 'claim-pa-pg',
      name: 'payment-db',
      kind: 'Postgres',
      status: 'Ready',
      class: 'postgres-standard-large',
      namespace: 'prod-payment-api',
      message: null,
      boundAt: '2026-05-29T09:00:00Z',
      endpoint: 'payment-db.internal.prod.svc.cluster.local:5432',
    },
    {
      id: 'claim-pa-redis',
      name: 'payment-cache',
      kind: 'Redis',
      status: 'Ready',
      class: 'redis-standard',
      namespace: 'prod-payment-api',
      message: null,
      boundAt: '2026-05-29T09:01:00Z',
      endpoint: 'payment-cache.internal.prod.svc.cluster.local:6379',
    },
    {
      id: 'claim-pa-bucket',
      name: 'payment-receipts',
      kind: 'Bucket',
      status: 'Ready',
      class: 'bucket-standard',
      namespace: 'prod-payment-api',
      message: null,
      boundAt: '2026-05-29T09:02:00Z',
      endpoint: 'https://payment-receipts.s3.kubernal.io',
    },
  ],
  'payment-api-staging': [
    {
      id: 'claim-pa-stg-pg',
      name: 'payment-db',
      kind: 'Postgres',
      status: 'Ready',
      class: 'postgres-standard-small',
      namespace: 'staging-payment-api',
      message: null,
      boundAt: '2026-06-01T10:30:00Z',
      endpoint: 'payment-db.internal.staging.svc.cluster.local:5432',
    },
    {
      id: 'claim-pa-stg-redis',
      name: 'payment-cache',
      kind: 'Redis',
      status: 'Binding',
      class: 'redis-standard',
      namespace: 'staging-payment-api',
      message: 'Waiting for provider resource to become ready',
      boundAt: null,
      endpoint: null,
    },
  ],
  'user-service-prod': [
    {
      id: 'claim-us-pg',
      name: 'user-db',
      kind: 'Postgres',
      status: 'Ready',
      class: 'postgres-highmem',
      namespace: 'prod-user-service',
      message: null,
      boundAt: '2026-05-27T07:00:00Z',
      endpoint: 'user-db.internal.prod.svc.cluster.local:5432',
    },
    {
      id: 'claim-us-bucket',
      name: 'user-avatars',
      kind: 'Bucket',
      status: 'Provisioning',
      class: 'bucket-standard',
      namespace: 'prod-user-service',
      message: 'Provisioning bucket, waiting for cloud provider',
      boundAt: null,
      endpoint: null,
    },
  ],
  'notification-svc-prod': [
    {
      id: 'claim-ns-redis',
      name: 'notification-queue',
      kind: 'Redis',
      status: 'Ready',
      class: 'redis-standard',
      namespace: 'prod-notification-svc',
      message: null,
      boundAt: '2026-05-31T12:30:00Z',
      endpoint: 'notification-queue.internal.prod.svc.cluster.local:6379',
    },
  ],
};

export const MOCK_HPA: Record<string, K8sHPAStatus> = {
  'payment-api-prod': {
    name: 'payment-api',
    minReplicas: 2,
    maxReplicas: 10,
    currentReplicas: 5,
    desiredReplicas: 5,
    cpuTarget: 70,
    cpuCurrent: 45,
    memoryTarget: null,
    memoryCurrent: null,
  },
  'payment-api-staging': {
    name: 'payment-api',
    minReplicas: 1,
    maxReplicas: 5,
    currentReplicas: 2,
    desiredReplicas: 2,
    cpuTarget: 80,
    cpuCurrent: 30,
    memoryTarget: null,
    memoryCurrent: null,
  },
  'user-service-prod': {
    name: 'user-service',
    minReplicas: 2,
    maxReplicas: 8,
    currentReplicas: 3,
    desiredReplicas: 3,
    cpuTarget: 70,
    cpuCurrent: 72,
    memoryTarget: null,
    memoryCurrent: null,
  },
  'notification-svc-prod': {
    name: 'notification-svc',
    minReplicas: 1,
    maxReplicas: 5,
    currentReplicas: 1,
    desiredReplicas: 2,
    cpuTarget: 60,
    cpuCurrent: 85,
    memoryTarget: null,
    memoryCurrent: null,
  },
};

export const MOCK_RESOURCES: Record<string, K8sContainerResources[]> = {
  'payment-api-prod': [
    {
      containerName: 'payment-api',
      cpuRequest: '250m',
      cpuLimit: '1000m',
      memoryRequest: '256Mi',
      memoryLimit: '1Gi',
      cpuUsage: '450m',
      memoryUsage: '680Mi',
    },
    {
      containerName: 'istio-proxy',
      cpuRequest: '100m',
      cpuLimit: '500m',
      memoryRequest: '128Mi',
      memoryLimit: '512Mi',
      cpuUsage: '80m',
      memoryUsage: '210Mi',
    },
  ],
  'payment-api-staging': [
    {
      containerName: 'payment-api',
      cpuRequest: '100m',
      cpuLimit: '500m',
      memoryRequest: '128Mi',
      memoryLimit: '512Mi',
      cpuUsage: '150m',
      memoryUsage: '280Mi',
    },
  ],
  'user-service-prod': [
    {
      containerName: 'user-service',
      cpuRequest: '500m',
      cpuLimit: '2000m',
      memoryRequest: '512Mi',
      memoryLimit: '2Gi',
      cpuUsage: '1440m',
      memoryUsage: '1.4Gi',
    },
    {
      containerName: 'istio-proxy',
      cpuRequest: '100m',
      cpuLimit: '500m',
      memoryRequest: '128Mi',
      memoryLimit: '512Mi',
      cpuUsage: '90m',
      memoryUsage: '195Mi',
    },
  ],
  'notification-svc-prod': [
    {
      containerName: 'notification-svc',
      cpuRequest: '200m',
      cpuLimit: '1000m',
      memoryRequest: '256Mi',
      memoryLimit: '1Gi',
      cpuUsage: '850m',
      memoryUsage: '780Mi',
    },
  ],
};

export const MOCK_K8S_SERVICES: K8sService[] = [
  {
    name: 'api-gateway',
    namespace: 'prod-gateway',
    type: 'LoadBalancer',
    clusterIP: '10.96.0.10',
    ports: [
      { name: 'http', port: 80, targetPort: 8080, protocol: 'TCP' },
      { name: 'https', port: 443, targetPort: 8443, protocol: 'TCP' },
    ],
    selector: { app: 'api-gateway' },
    status: 'Active',
    createdAt: '2026-05-20T08:00:00Z',
  },
  {
    name: 'auth-service',
    namespace: 'prod-auth',
    type: 'ClusterIP',
    clusterIP: '10.96.1.20',
    ports: [
      { name: 'http', port: 8080, targetPort: 8080, protocol: 'TCP' },
    ],
    selector: { app: 'auth-service' },
    status: 'Active',
    createdAt: '2026-05-22T10:00:00Z',
  },
  {
    name: 'user-service',
    namespace: 'prod-user-service',
    type: 'ClusterIP',
    clusterIP: '10.96.2.30',
    ports: [
      { name: 'http', port: 8080, targetPort: 8080, protocol: 'TCP' },
    ],
    selector: { app: 'user-service' },
    status: 'Active',
    createdAt: '2026-05-27T07:00:00Z',
  },
  {
    name: 'payment-service',
    namespace: 'prod-payment-api',
    type: 'ClusterIP',
    clusterIP: '10.96.3.40',
    ports: [
      { name: 'http', port: 8080, targetPort: 8080, protocol: 'TCP' },
    ],
    selector: { app: 'payment-api' },
    status: 'Active',
    createdAt: '2026-05-29T09:00:00Z',
  },
  {
    name: 'postgres-primary',
    namespace: 'prod-database',
    type: 'ClusterIP',
    clusterIP: '10.96.4.50',
    ports: [
      { name: 'postgres', port: 5432, targetPort: 5432, protocol: 'TCP' },
    ],
    selector: { app: 'postgres', role: 'primary' },
    status: 'Active',
    createdAt: '2026-05-15T06:00:00Z',
  },
  {
    name: 'redis-cache',
    namespace: 'prod-cache',
    type: 'ClusterIP',
    clusterIP: '10.96.5.60',
    ports: [
      { name: 'redis', port: 6379, targetPort: 6379, protocol: 'TCP' },
    ],
    selector: { app: 'redis', role: 'cache' },
    status: 'Active',
    createdAt: '2026-05-18T09:00:00Z',
  },
  {
    name: 'rabbitmq',
    namespace: 'prod-messaging',
    type: 'NodePort',
    clusterIP: '10.96.6.70',
    ports: [
      { name: 'amqp', port: 5672, targetPort: 5672, protocol: 'TCP', nodePort: 30672 },
      { name: 'management', port: 15672, targetPort: 15672, protocol: 'TCP', nodePort: 31672 },
    ],
    selector: { app: 'rabbitmq' },
    status: 'Active',
    createdAt: '2026-05-16T11:00:00Z',
  },
  {
    name: 'monitoring-prometheus',
    namespace: 'monitoring',
    type: 'ClusterIP',
    clusterIP: '10.96.7.80',
    ports: [
      { name: 'http', port: 9090, targetPort: 9090, protocol: 'TCP' },
    ],
    selector: { app: 'prometheus' },
    status: 'Active',
    createdAt: '2026-05-10T08:00:00Z',
  },
  {
    name: 'ingress-nginx',
    namespace: 'ingress-nginx',
    type: 'LoadBalancer',
    clusterIP: '10.96.8.90',
    ports: [
      { name: 'http', port: 80, targetPort: 80, protocol: 'TCP' },
      { name: 'https', port: 443, targetPort: 443, protocol: 'TCP' },
    ],
    selector: { app: 'ingress-nginx' },
    status: 'Active',
    createdAt: '2026-05-08T07:00:00Z',
  },
];

const now = new Date();

function minutesAgo(m: number): string {
  return new Date(now.getTime() - m * 60_000).toISOString();
}

export const MOCK_EVENTS: K8sEvent[] = [
  {
    id: 'evt-1',
    involvedObject: 'pod/payment-api-7f8b9c-v9z',
    reason: 'FailedScheduling',
    message: 'Insufficient cpu (4 requested, 2 available) on node node-05',
    type: 'Warning',
    count: 3,
    lastTimestamp: minutesAgo(2),
    source: 'default-scheduler',
  },
  {
    id: 'evt-2',
    involvedObject: 'pod/user-service-4d5e6f-h5t',
    reason: 'Unhealthy',
    message: 'Liveness probe failed: HTTP probe failed with statuscode 503',
    type: 'Warning',
    count: 12,
    lastTimestamp: minutesAgo(5),
    source: 'kubelet',
  },
  {
    id: 'evt-3',
    involvedObject: 'pod/user-service-4d5e6f-h5t',
    reason: 'BackOff',
    message: 'Back-off restarting failed container user-service',
    type: 'Warning',
    count: 15,
    lastTimestamp: minutesAgo(3),
    source: 'kubelet',
  },
  {
    id: 'evt-4',
    involvedObject: 'pod/notification-svc-9g1h2i-u7e',
    reason: 'Killing',
    message: 'Container notification-svc failed with exit code 137',
    type: 'Warning',
    count: 4,
    lastTimestamp: minutesAgo(8),
    source: 'kubelet',
  },
  {
    id: 'evt-5',
    involvedObject: 'pod/payment-api-7f8b9c-v9z',
    reason: 'SuccessfulCreate',
    message: 'Created container payment-api',
    type: 'Normal',
    count: 1,
    lastTimestamp: minutesAgo(1),
    source: 'replicaset-controller',
  },
  {
    id: 'evt-6',
    involvedObject: 'pod/payment-api-7f8b9c-x2k',
    reason: 'Started',
    message: 'Started container payment-api',
    type: 'Normal',
    count: 1,
    lastTimestamp: minutesAgo(25),
    source: 'kubelet',
  },
  {
    id: 'evt-7',
    involvedObject: 'pod/payment-api-7f8b9c-m4p',
    reason: 'Pulled',
    message: 'Container image "kubernal/payment-api:v2.1.0" already present on machine',
    type: 'Normal',
    count: 2,
    lastTimestamp: minutesAgo(20),
    source: 'kubelet',
  },
  {
    id: 'evt-8',
    involvedObject: 'pod/user-service-4d5e6f-j2m',
    reason: 'Started',
    message: 'Started container user-service',
    type: 'Normal',
    count: 1,
    lastTimestamp: minutesAgo(15),
    source: 'kubelet',
  },
  {
    id: 'evt-9',
    involvedObject: 'deployment/notification-svc',
    reason: 'SuccessfulCreate',
    message: 'Scaled up replica set notification-svc-9g1h2i to 2',
    type: 'Normal',
    count: 1,
    lastTimestamp: minutesAgo(10),
    source: 'deployment-controller',
  },
  {
    id: 'evt-10',
    involvedObject: 'pod/notification-svc-9g1h2i-r3y',
    reason: 'Pulled',
    message: 'Container image "kubernal/notification-svc:v1.4.0" already present on machine',
    type: 'Normal',
    count: 1,
    lastTimestamp: minutesAgo(18),
    source: 'kubelet',
  },
  {
    id: 'evt-11',
    involvedObject: 'deployment/payment-api',
    reason: 'SuccessfulCreate',
    message: 'Scaled up replica set payment-api-7f8b9c to 5',
    type: 'Normal',
    count: 1,
    lastTimestamp: minutesAgo(4),
    source: 'deployment-controller',
  },
  {
    id: 'evt-12',
    involvedObject: 'deployment/notification-svc',
    reason: 'FailedScheduling',
    message: 'Insufficient memory (1Gi requested, 512Mi available) on node node-05',
    type: 'Warning',
    count: 5,
    lastTimestamp: minutesAgo(12),
    source: 'default-scheduler',
  },
  {
    id: 'evt-13',
    involvedObject: 'deployment/payment-api',
    reason: 'SuccessfulCreate',
    message: 'HorizontalPodAutoscaler scaled deployment to 5 replicas',
    type: 'Normal',
    count: 2,
    lastTimestamp: minutesAgo(6),
    source: 'horizontal-pod-autoscaler',
  },
  {
    id: 'evt-14',
    involvedObject: 'pod/user-service-4d5e6f-w8q',
    reason: 'Started',
    message: 'Started container istio-proxy',
    type: 'Normal',
    count: 1,
    lastTimestamp: minutesAgo(22),
    source: 'kubelet',
  },
  {
    id: 'evt-15',
    involvedObject: 'deployment/user-service',
    reason: 'SuccessfulCreate',
    message: 'HorizontalPodAutoscaler scaled deployment to 3 replicas',
    type: 'Normal',
    count: 1,
    lastTimestamp: minutesAgo(9),
    source: 'horizontal-pod-autoscaler',
  },
];
