apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubernal-dev
resources:
  - ../../k8s/base
images:
  - name: ghcr.io/gowaru/kubernal-api
    newTag: sha-4b06def
  - name: ghcr.io/gowaru/kubernal-backstage
    newTag: latest
