---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgres-secret
  namespace: kubernal-dev
spec:
  encryptedData:
    POSTGRES_DB: AgCIcWsoxEKyD9CcCUVMbDZ6jYfZES0TUUzfCDGFRflt0WnDYH/Qzv6/PFaR7UDSsC6F1BKBOJGgfxyJhrBqQqLUBarFdAwVyVWKWTrn7LEJajqnA7X9NsmNIdJDQHYsoF1l+488jLOVzL5KzrAMNyxW/OQwvAR4HOtEJDh1VZviX+HryqaI99a0HSc3VHb+TvdozTg8YIaCVGu33dISRHiO2Tj2YK/86a1VlhQ3vlfpPCJnpJ5iaxRO7yH/Fz1XxP5S4m9InN32klTUK7fivwWm/ooO2vgkraDlcwZvGRNGPIK7UiNBCXTgbCA20GK9sJqkQigjrQ0+BAyCpFrBxBUDoQZ4I3HHXMAG/oinDnOIW3ouqC4aquTdAXe9vRY4zifqaIytNtH0zSNTtseTg5885D95FmwFxUScESY6VINtPcXumddHMkpZpPGjwMIWAZ1Q0WHAb0I6cMjfekPev9sJLxDNrnC80/XM05250McpMqHc5wHBi91APLm6Xt6IXTMRGUtRzyUOibvzRL/FboC8LrRMaT5Le5t1jlO5lBtbno6m0z27wXw0t2GbyL5b5nIQRtVBFr7rIfC82Abio3O6Pr27UzCpTsCjYRMkAlEAYeQGA5g8iASqlXLu20mk3yJkjlxLeggNyquXZXBE0YR5rv1OeP+CBZLhR9p/UszZLhlybnvbwOcsrOdZzzVSpzIe/Vj/ZayJf1yYAaY=
    POSTGRES_PASSWORD: AgBiOzfvKAZ2dt+mx0W8WZLrhj0i9q3uHrPNKvzg8xYKSkcfXOfnLdoXtLCF+dL2H8SRA2mzUVPppPISPNNl3LdD/WXjheW2yskjKoV0lf9ApqivJyNs6BanQq95VIzVw6n9TGopqtCKSzZFtRauDTiMfRLt5B1Z4az+/VrjK0LEsr7XNb2HT5x0SaV55hMs2itlBg1RbMhgF6zgOabo0pS0meaFrHDE2ARffeh+biayEWZkUO8JlouNDcM8NBoHgAmS64oN+qScO6wJ4SsPRoTURbnJZL2/Q7pP++41um9+mEieMcTFPh3rpn7Q3j/TdMTpIiTu1qUOD8mzuipYLASACVAf4+sU1qCxDXtCi+kkV7IDv7rWY1FOQXKMMOQFwaGcqOIYtNRgEqYtp0EX2p7fLHWdysMEY0wIDJ+NAo7wV9xh8Zq0ixG6zywC6jKZ04kAi6iiGSL9pubWtYQoXaw8gNr/CAYf+T9unlPIN1aj7yxoUT+BG4ZWX9f5xg7TLLPVztWTXvihL6jgHGelrX1rpzyjg3RDnA7oq52TyIxQYe9+RlyrZQXUB4Z+3Z4EFXoCk63TZ4UVpR8ip1PFB400nO8q0ak1PZSt64JjyfcLxYQFa5Y8sx5iHAn7W09XjEnuuxiHGuQWNuDQOeG4MU0vIHUq0Aia91yjMjdTYnrLblpi0sFQ5H63433cIyVHE+ed7OtVWonhwOHt4FM=
    POSTGRES_USER: AgB2HmY5ohBKOjlqukOZYZTEL1vfl+7NkCtPBy50e6h0T4A4UvO1ciEIJJ8NJ4v+o0ZdltCr+LOvXeCVbEyf5U6McMP7dJQj1ifcMeeyf9Il7vr49diw9m91HoC/BUmVAOi01gFkVZeAsPGTmZync8IurUP3tD31PTMTrKp8an7IcKfW5ULo72bEA9R0eE71TqhJVcaf/ppb79EJbpvTJzLevELZO/0xb1+nSBnQpjmfCZaIWMgPW6/CtymnzfoRdoAiA36UeZgDFeX2gfFQhvGTROCLzMiCXZQ2PrK6jOMNB3Fnld/yHQS8Tps5Og2dUi8XRrKfiD0MG2oPAl/xCJ4vlJLH9tcewlulDih6RxPZLXp25Pe6V3M2RWrXBeKgvKlxGfNlJ+ljs1LfesQplI1XrzCn/DYRMbWpV+SWjyzis/KvnVgmY++cGM9avoe/6nIC/8Z5sKezS6LlqsU7LBdCnkJD5dc5GYMV7KjuM+gwQq5Rbsi1pVNpjt+VeeKKnRoVTRfbul9k1DGHfTqX1ZFGVLhL7Guy/sdU1xkCdLC0J9PxwvOlaRZJ+BMSd9eK/uSfFC4cW02j6DGrL/YDtq0sMmfEzOYiCbRB1KNJbltEGSOLhm5HNdwYuA05kA8/p7qnOAwHnfG4HK4q9VRTs+RlrPtNBQQ/JtuRM2OfDZi5SMFsCU4Qai8N4Omg8Gpr4/Mdi4zulGIN3g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: postgres
        kubernal.io/managed-by: kubernal
      name: postgres-secret
      namespace: kubernal-dev
    type: Opaque
