apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernal-api-dev
  namespace: argocd
  labels:
    kubernal.io/component: api
    kubernal.io/environment: dev
    kubernal.io/managed-by: kubernal
spec:
  project: kubernal
  source:
    repoURL: 'https://github.com/Gowaru/kubernal'
    targetRevision: main
    path: infra/kubernetes/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubernal-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
