apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubernal-staging

resources:
  - ../../api/configmap.yaml
  - ../../api/secret.yaml
  - ../../api/deployment.yaml
  - ../../api/service.yaml
  - ../../backstage/configmap.yaml
  - ../../backstage/secret.yaml
  - ../../backstage/deployment.yaml
  - ../../backstage/service.yaml

patches:
  - target:
      kind: Deployment
      name: kubernal-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: backstage
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
