---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgres-secret
  namespace: kubernal-prod
spec:
  encryptedData:
    POSTGRES_DB: AgC6AC/GU0plt3gDJeiHJxDG2B7jcqjxaa5k3ZrmZotgBX6XABJXNshyTuGIE4jzUxGH97uGeTLy1Sia/S9UavSAEjpWg4GIPQWIhUpjwjmvdqOzby/1N/dVMKmyKDP3a33bYhfnNSV0YdAPusIzwIPAYQjpLMyag5p5+u3E2bzQ5mFrjbhzpnHoVZeXE5ex7zTtKQi/EXwc1gl3aYfwbQOXDNFLOmIJJ5Tc94GbPfe4eIPNqkSQiR9ol6rGjSgKiapcAWwVEiO/jFga5bbDdFNFdDsrT8FCxS4JVHbWLGL+BxoyH4BMvC913kZxy0cufx/eaVeQj+07SxfYmPP4nz9KvivcZjpEHe81i4nFaiMwAnZ6MEk9Z6tbrqQQAS8QQKRwyiYZGK4VYkBjw9k7A6I+Yxea83ynu6yV64u7mpNLLs2fYleqxg5SfjMs74z9op/+RKRAJTHU2xb1nHGKg496hbz/t4tmpvyR1wHKlscsFoRtSFS+r1Z5+YypY8jlkiIhtYRU66F7evRNQzGl764eZ0V5czvkr5A2KDkvAUwKn0iJBal9cZ7fHejTDV8pxQN7l8Nc4JsGzzmTqyJbzl4lzeuuBlMGQeJpmB4Y95hEaeS1tczD6jNkwGsd+sX8kfJPw60fcubkMWFc1oHNnMWSYQkdk7vNNFBFwOEyoFE5K/rPnrCK/dYRML0oWS00qm+tvjlNPKF+reVpqeA=
    POSTGRES_PASSWORD: AgC0jAN47Gq+PBwwK3hZfifJoRPjGss4egMGzLgUYfQrEuRK2dF2tDR2DLDNdAiT/AvIaHbNdIDvdcena8xgKFOG08GcwHs/DznJQCoPGcvBAiMjGvkFWa3PPfcpL/Gm1Iuc5eQWCxQp+Mf/XpkGFvHg8022sqFLwLEGuD9WFawTsQQvPA5K7sMYHowl+u7J1ZC3s5+Uss8yC+vFVbuUPeUQt+S5KXsVscIWAWtM3MGA/5Vsnw23MVC3MyxJFYdlGWH3AAo0Uzfs+xmreraVa1UDW66mA+0dzOf3potBanAUZURc6erO5Dq+m98kvC16C9Wl9qS7u1arwLgH+8RG+8FUS0jDh/W75I/jJQKb1ZCMmLwfiZ1+bfndHhPldqGIa4e2YIbX2Fv8ELHqu80JEJ071viFFg6Dz79pND4eCB3e8x1qKqgzyNphcU28/Bknld7TJHcqi1UIPU3FhzhkmdffjeUroUNzhweTtLRMeArbEXxukTxHiZnAy0A0e5cHIimjgxBmFLXKjFyPjI7hp9zObV/7Yav4QcKn1TdDivKlUw7gIGzF2fijxG5y6zzLB7WaOcwj5N9EhYp4lQ0hz28rWTd+/LVxdTjPmuFRlJHCoJX9QfNmNHWZFw5/WSvwL2IOY1tEAGON2zUxemVU9vkV6+ijEl2kwsnItB+3LH+LsaxBeh3mJsNfm+H4wcnTxR9WFIstpWKq43rBhEOx
    POSTGRES_USER: AgBuI0bCYnxYaR7vjeJX3by6FRwnEcYFcDlpFzGz4qLLSCR2Snj7U/QDOBxXswCwGEgJkapSnJ6+yOzjZctOFnunr3QeT7lP6UH8BjECBKDAnoLAsGNvxij73EkU9KspF4Q0vy+KECTqTX3Yh5r7udmJv3S2PW+gGGuOLhcqVASFbvPV2BQHWQnJnqQAMA/rwJ15Ywehjos8x+a5dkW9fcAeFni2dmxzuAXO993hsR4N7i1vSJvCxH8Z21Ie2mN+ruywQ/ffiBRlIntWhPbGaoVSorPNMf030A3cauYJ7bgz3VYBf1xxiAuIebBw0alIYi4JvdTW94QgJFqyZwWxGSw+icPPIAvdm7P9jTrXxfpkn7Ofbdm3GkkNuXo0lLvNwL4ecQIW5s2XQss05kxfbWXf9p9pLQCPBwbra2LgAq3F0CNypNKZZ0dHWexxAfZRyI0W5bi70OnUwv2S1OlhGOv+Tzy/l6C/Fod2j3pIsGtw02ao8ss0SmI8scgqt9PxXrZfb56r/P0MzlQcLghJiUHmGTgZoBsNweX/WbtAx6p2vpE6IX2mIpYKTxTe4imW5h2rMXsWBVjEhLF6Flo3L+Ftdio5+BCCvrY0W/HYnIouxNaNL9jbqtCKkgac4K9cxHV5jJbyPvg61jzZgfSoKV4431C9k/cJTj1oJH4866yx4/pZOViggzIotaLLRPtl6yDshzXxtkAB2A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: postgres
        kubernal.io/managed-by: kubernal
      name: postgres-secret
      namespace: kubernal-prod
    type: Opaque
