---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgres-secret
  namespace: kubernal-prod
spec:
  encryptedData:
    POSTGRES_DB: AgC+T7pMHKycbP4/ZMW0dNBkEiRinj50mIl19MSYdz47FNF1vTzDxxRQFw1EJYG+RbzuPI+2HOhGhs3wl7IUYhkZeaJjVWipQjN2ukTjLiKRcwhdP/7zsOjjb5zrNdxt7zvzBvBqWsrZVEK2vpycgLu/AB1Kr/irTAF7RshHoevahNbAoLtB1oAKW0lqG9xUjEYFwtea6nhcx50nKpgbaJbNk8ThLYFszVkjDDXKGTWd4EdO/J0CX3EP09crXcvbpO8G+pIVjx5+XaBIXta0uMQlt/76YDwcRegmzasWN7uEm0zc/tthtGh9k4RfsmeHOWvXQKnd+Aemn6trxy5B0zDOrQjlTiQwT4SJwsCa+mIqCQz0ENHXuFlV5mEI9Kiw6OVfLv5YZQl7e2N3i0UZ7TW5ywtcMmOoZvsJuSIiC9sedQXTC77Ax/V7oZv1FEEuRMv+f91CW63dDb01XKbtPPPVz42XoXP9xRF57c2mxfQHs7dGXUSxeFHe8uPb16mbGn3ty0NFS4+TRkfNvNnFHdYRpotGYtnt9RMa/sP6s6Ni87iDE5ihXXDBhUAL6QaM9uhNCaZCq8t2DSuhnRL98+SkW23UP7uq1dVfu8Ob5jIgcBHqXvr+IJeFOhWbR1Q9KlRQBtc+S0Pa/iyWoIItFtmt41tDtBUaIV8dKQdei45Iq5XNbk9/O82ACQHFaA4fJCgRrGpspybolZnWgBA=
    POSTGRES_PASSWORD: AgAoVqe46+EdtU9gZPXvoMzh6FD0t1CFZx6GhcR0GxP3a3cdK49hdUJplDuF8dlSF7Lc2VB7ckVXziLYrb0jzywAXdejsM9eZJjCb0l/iqxjK/jIpJTHbxh/5hTBpsB/gsdFWjfy1Tc8quMG3eXhFMwmIJDR1B/T6OyUUXSKccy02pG/EjV6ttgBxYkn5oF/JX/a5RO0hJA7m0BopBYMl/EGEi3bbmRICGNWDTWK0sIsmAwW0M6rCLAS4PQI/uCyzjlyue1PYg7fVkoOtX5hs+eSIPsIU1y0pa9/a9P115GR1h/wVPE8S5WJgnE1HM2AAdraHLinxFv/dTFCEs8a7+Tj09em/6TKxmGiP7Wr5T5DTs71q3qfE/fO/3tQJif3Pv7FepNCidIbOi1AL8+Utbb8nDIOBlnEGs6wrAWHZZskSS9G602rbo8zn26xRuG8Ab6uwSpDjXKkzkHGhO8ECbx/8lZBXVKSrK15/ceDeIwUSeIwobsDcYjP0qIfDUCd7j11M0ERFiYvwRkhEtRFdDftHVcOWVz7Hg9xdLqdPjwOIxkg1wa1CGJuvpn+CFPVlGzc9bdy/z1pbXOqITlGVpYrUndUPQmkj2US/FgBHxid9iAbJ07lWFlVeic/g8WIwAdENz4iwpnTOuYvBvOocKIkbE/MtElNDfNIg7mH28kOKlL0S9lqfXBbj2y5YFe9k9ZVK6/32YKkTEoKasf76VjmHDPPrgvIQgc=
    POSTGRES_USER: AgBRQx2jRC0eigpHgyL7tbCLdZWNCn8T0S9KkBHMLdUx+Z95+Lj7A+GL+vT5Ic2WmhRf0t1heh45ri3SMgMJ0VsqzdfhdzK1p2hFjZQl4jqeEzGYjiRJPtXCUniWmbhv/8l+VOqdS8qtg0AuN6QKBUlPVpAAFBrrvrcwCdRqPRGSBz593iCAaqX/BxVyF7NgVVeTzx1QhJawt7t3qTeEwaL0EgGG1xEt69DMDDHWz/Lm3zrKnXsVWr0S07JlICi8sJPwyH3/Q9FFuoNVTvQYpnVShsa2FCpIBtGlKOd8yxZDm2Asy1MckUXmkEo4YqvXb7mdUqA57p9lY0N68Y5InAHOXG+H7Kb8iHyiCIa0MX4FDtEHkk6g9VPcZQzyuAjZ/ZuuJwVygwf2/tHKC0OkdXrf2cvO3UuRx0ZS23bpFr1c5ngLHbvXZnC2E55YPBLxpd4j/QXov9usnBT6eWL89g0uZBt7AfL5rYLMt0F+w00nHaf1Shm0JJUN10kSKOGnbGViFekvV0cWgupqO4BoItor+dVjU2DqZneDsB5wAMoX1GBDFCs9GcYRh64l/UOo2Cee4wHS0ZGk6Ng5ejL37PUZMzlS0Sk7JfsEurwidRQMiHlkN+xQ9DgySb1sYBJnsYqWcxZqkegXDO3cjqz7hFhY09W4Yy4x/p+pi/l5Z35t+48UYILb9AyPpyuZkzYvYDSCGRYFl7uY5A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: postgres
        kubernal.io/managed-by: kubernal
      name: postgres-secret
      namespace: kubernal-prod
    type: Opaque
